// Structured, backend-ready location data model for JAL-DRISHTI.
//
// The UI reads the selected location from application state:
//   selectedLocationId  ->  locations[selectedLocationId]
//
// This object map is intentionally decoupled from the UI so that a real
// ML / backend API can later replace `locations` without touching components.
// All numeric values here are DEMO / SIMULATED unless sourced from live sensors.

import type { LatLng, LiveMetrics, RiskLevel } from './disaster-data'

export type Coverage = 'full' | 'limited' | 'none'
export type LocationKind = 'flood' | 'glacier' | 'lake'

export interface LocationRecord {
  id: string
  kind: LocationKind
  name: string
  country: string
  state: string // State / Province
  district: string // District / region
  coord: LatLng // [lat, lng]
  isDemoArea: boolean // part of the SIH (Uttarakhand) demonstration area
  coverage: Coverage // prediction-data availability
  demo: boolean // values are simulated (true for the whole prototype)

  // Exposure
  population: number
  elevationM: number

  // Prediction
  floodProbability: number // 0-100
  risk: RiskLevel
  leadTimeMin: number
  confidence: number // 0-100

  // Drivers (latest reading)
  rainfall: number // mm/h
  soilMoisture: number // %VWC
  riverLevel: number // m
  riverDanger: number // m
  slopeStability: number // 0-100 (higher = more stable)

  // Context
  historicalRisk: string
  nearbyRiver: string
  nearbySensors: string[]
  alertStatus: string
  recommendedAction: string
}

// View presets for the global -> local navigation controls.
export const MAP_VIEWS = {
  global: { label: 'Global', center: [20, 10] as LatLng, zoom: 2 },
  india: { label: 'India', center: [22.6, 79] as LatLng, zoom: 5 },
  uttarakhand: { label: 'Uttarakhand', center: [30.05, 79.1] as LatLng, zoom: 8 },
  demo: { label: 'SIH Demo Area', center: [30.288, 78.98] as LatLng, zoom: 12 },
} as const

export type MapViewKey = keyof typeof MAP_VIEWS

export const VIEW_PRESETS: { key: MapViewKey; label: string }[] = [
  { key: 'global', label: 'GLOBAL' },
  { key: 'india', label: 'INDIA' },
  { key: 'uttarakhand', label: 'UTTARAKHAND' },
  { key: 'demo', label: 'SIH DEMO' },
]

// Prediction-coverage footprints (visualised by the "Prediction Coverage" layer).
export interface CoverageRegion {
  id: string
  name: string
  coverage: Coverage
  polygon: LatLng[]
}

export const coverageRegions: CoverageRegion[] = [
  {
    id: 'cov-demo',
    name: 'Rudraprayag Demonstration Grid (full)',
    coverage: 'full',
    polygon: [
      [30.42, 78.86],
      [30.42, 79.12],
      [30.15, 79.12],
      [30.15, 78.86],
    ],
  },
  {
    id: 'cov-uk',
    name: 'Uttarakhand Operational Coverage (full)',
    coverage: 'full',
    polygon: [
      [31.2, 77.9],
      [31.2, 80.2],
      [29.5, 80.2],
      [29.5, 77.9],
    ],
  },
  {
    id: 'cov-himalaya',
    name: 'Himalayan Extension (limited / pilot)',
    coverage: 'limited',
    polygon: [
      [32.2, 76.0],
      [32.2, 88.5],
      [26.5, 88.5],
      [26.5, 76.0],
    ],
  },
]

// ---- Location records ------------------------------------------------------
// Uttarakhand / Rudraprayag SIH demo settlements (full coverage) + a small set
// of additional locations to demonstrate global interaction and mixed coverage.

const records: LocationRecord[] = [
  {
    id: 'v-1',
    kind: 'flood',
    name: 'Rudraprayag Town',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    coord: [30.2865, 78.9805],
    isDemoArea: true,
    coverage: 'full',
    demo: true,
    population: 9313,
    elevationM: 610,
    floodProbability: 87,
    risk: 'critical',
    leadTimeMin: 42,
    confidence: 93,
    rainfall: 62,
    soilMoisture: 91,
    riverLevel: 4.8,
    riverDanger: 5.2,
    slopeStability: 34,
    historicalRisk: 'Severe — 2013 Kedarnath disaster impact corridor',
    nearbyRiver: 'Mandakini–Alaknanda confluence',
    nearbySensors: ['RG-01 Confluence', 'RN-04 Silli Ridge'],
    alertStatus: 'CRITICAL — flash flood imminent',
    recommendedAction: 'Immediate evacuation of left-bank wards via Route E-1 to Ridge Shelter.',
  },
  {
    id: 'v-2',
    kind: 'flood',
    name: 'Silli',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    coord: [30.297, 78.973],
    isDemoArea: true,
    coverage: 'full',
    demo: true,
    population: 1240,
    elevationM: 640,
    floodProbability: 81,
    risk: 'critical',
    leadTimeMin: 38,
    confidence: 90,
    rainfall: 59,
    soilMoisture: 88,
    riverLevel: 4.6,
    riverDanger: 5.0,
    slopeStability: 38,
    historicalRisk: 'High — recurrent bank erosion',
    nearbyRiver: 'Mandakini',
    nearbySensors: ['RN-04 Silli Ridge', 'RG-01 Confluence'],
    alertStatus: 'CRITICAL — evacuation advised',
    recommendedAction: 'Evacuate riverside households; move to designated Silli ridge muster point.',
  },
  {
    id: 'v-3',
    kind: 'flood',
    name: 'Kaliasaur',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    coord: [30.307, 79.004],
    isDemoArea: true,
    coverage: 'full',
    demo: true,
    population: 860,
    elevationM: 720,
    floodProbability: 64,
    risk: 'elevated',
    leadTimeMin: 66,
    confidence: 88,
    rainfall: 48,
    soilMoisture: 84,
    riverLevel: 4.1,
    riverDanger: 4.8,
    slopeStability: 42,
    historicalRisk: 'High — chronic landslide / slope-failure belt',
    nearbyRiver: 'Alaknanda',
    nearbySensors: ['SP-02 Kaliasaur', 'IN-03 Slope Array'],
    alertStatus: 'WARNING — landslide-dam breach watch',
    recommendedAction: 'Restrict NH-107 traffic; stage QRT and monitor inclinometer drift.',
  },
  {
    id: 'v-4',
    kind: 'flood',
    name: 'Jawari',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    coord: [30.268, 78.992],
    isDemoArea: true,
    coverage: 'full',
    demo: true,
    population: 540,
    elevationM: 780,
    floodProbability: 41,
    risk: 'caution',
    leadTimeMin: 95,
    confidence: 85,
    rainfall: 33,
    soilMoisture: 76,
    riverLevel: 3.4,
    riverDanger: 4.6,
    slopeStability: 55,
    historicalRisk: 'Moderate — monsoon saturation events',
    nearbyRiver: 'Alaknanda left bank',
    nearbySensors: ['SP-05 Jawari', 'RG-02 Alaknanda'],
    alertStatus: 'WATCH — rainfall accumulation advisory',
    recommendedAction: 'Open community shelter; brief village disaster committee.',
  },
  {
    id: 'v-5',
    kind: 'flood',
    name: 'Bhanigram',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    coord: [30.259, 78.986],
    isDemoArea: true,
    coverage: 'full',
    demo: true,
    population: 720,
    elevationM: 810,
    floodProbability: 37,
    risk: 'caution',
    leadTimeMin: 110,
    confidence: 84,
    rainfall: 29,
    soilMoisture: 73,
    riverLevel: 3.2,
    riverDanger: 4.6,
    slopeStability: 58,
    historicalRisk: 'Moderate — terrace runoff',
    nearbyRiver: 'Alaknanda left bank',
    nearbySensors: ['SP-05 Jawari', 'RG-02 Alaknanda'],
    alertStatus: 'WATCH — monitor overnight rainfall',
    recommendedAction: 'Pre-position resources; keep shelter on standby.',
  },
  {
    id: 'v-6',
    kind: 'flood',
    name: 'Devli',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    coord: [30.326, 78.96],
    isDemoArea: true,
    coverage: 'full',
    demo: true,
    population: 410,
    elevationM: 1120,
    floodProbability: 12,
    risk: 'safe',
    leadTimeMin: 180,
    confidence: 91,
    rainfall: 18,
    soilMoisture: 61,
    riverLevel: 2.6,
    riverDanger: 4.6,
    slopeStability: 74,
    historicalRisk: 'Low — well-drained ridge',
    nearbyRiver: 'Ridge catchment (no major channel)',
    nearbySensors: ['WX-01 Ridge Station'],
    alertStatus: 'NOMINAL — designated ridge shelter',
    recommendedAction: 'No action. Available as reception / muster site for evacuees.',
  },
  // ---- Additional locations for global demonstration -----------------------
  {
    id: 'g-1',
    kind: 'flood',
    name: 'Joshimath',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Chamoli',
    coord: [30.5556, 79.5646],
    isDemoArea: false,
    coverage: 'full',
    demo: true,
    population: 16709,
    elevationM: 1875,
    floodProbability: 58,
    risk: 'elevated',
    leadTimeMin: 74,
    confidence: 82,
    rainfall: 41,
    soilMoisture: 80,
    riverLevel: 3.9,
    riverDanger: 4.9,
    slopeStability: 36,
    historicalRisk: 'High — active land subsidence + GLOF exposure',
    nearbyRiver: 'Alaknanda / Dhauliganga',
    nearbySensors: ['Regional gauge (pilot)'],
    alertStatus: 'WARNING — slope & subsidence watch',
    recommendedAction: 'Monitor subsidence markers; restrict heavy construction zones.',
  },
  {
    id: 'g-2',
    kind: 'flood',
    name: 'Guwahati',
    country: 'India',
    state: 'Assam',
    district: 'Kamrup Metropolitan',
    coord: [26.1445, 91.7362],
    isDemoArea: false,
    coverage: 'full',
    demo: true,
    population: 957352,
    elevationM: 55,
    floodProbability: 52,
    risk: 'elevated',
    leadTimeMin: 130,
    confidence: 79,
    rainfall: 38,
    soilMoisture: 82,
    riverLevel: 6.4,
    riverDanger: 7.2,
    slopeStability: 68,
    historicalRisk: 'High — annual Brahmaputra flooding',
    nearbyRiver: 'Brahmaputra',
    nearbySensors: ['Regional gauge (pilot)'],
    alertStatus: 'WARNING — river level rising',
    recommendedAction: 'Activate urban drainage protocol; monitor embankment integrity.',
  },
  {
    id: 'g-3',
    kind: 'flood',
    name: 'Pokhara',
    country: 'Nepal',
    state: 'Gandaki',
    district: 'Kaski',
    coord: [28.2096, 83.9856],
    isDemoArea: false,
    coverage: 'limited',
    demo: true,
    population: 200000,
    elevationM: 822,
    floodProbability: 45,
    risk: 'caution',
    leadTimeMin: 150,
    confidence: 61,
    rainfall: 34,
    soilMoisture: 77,
    riverLevel: 3.6,
    riverDanger: 4.7,
    slopeStability: 49,
    historicalRisk: 'Moderate — Seti River flash floods (limited sensor coverage)',
    nearbyRiver: 'Seti Gandaki',
    nearbySensors: ['Pilot telemetry (sparse)'],
    alertStatus: 'WATCH — limited data confidence',
    recommendedAction: 'Treat prediction as indicative only; corroborate with local observers.',
  },
  // ---- Glacier monitoring sites (simulated prototype records) ---------------
  {
    id: 'gl-chorabari',
    kind: 'glacier',
    name: 'Chorabari Glacier',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    coord: [30.746, 79.061],
    isDemoArea: true,
    coverage: 'full',
    demo: true,
    population: 0,
    elevationM: 3890,
    floodProbability: 72,
    risk: 'elevated',
    leadTimeMin: 90,
    confidence: 64,
    rainfall: 22,
    soilMoisture: 68,
    riverLevel: 2.1,
    riverDanger: 4.6,
    slopeStability: 41,
    historicalRisk: 'High — 2013 glacial-lake outburst contribution (prototype scenario)',
    nearbyRiver: 'Mandakini headwaters',
    nearbySensors: [],
    alertStatus: 'WARNING — elevated melt / GLOF watch (simulated)',
    recommendedAction: 'Treat as prototype GLOF watch; corroborate before operational use.',
  },
  {
    id: 'gl-gangotri',
    kind: 'glacier',
    name: 'Gangotri Glacier',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Uttarkashi',
    coord: [30.932, 79.081],
    isDemoArea: false,
    coverage: 'full',
    demo: true,
    population: 0,
    elevationM: 4120,
    floodProbability: 48,
    risk: 'caution',
    leadTimeMin: 160,
    confidence: 61,
    rainfall: 18,
    soilMoisture: 55,
    riverLevel: 1.8,
    riverDanger: 4.2,
    slopeStability: 52,
    historicalRisk: 'Moderate — long-term retreat of Bhagirathi source (simulated)',
    nearbyRiver: 'Bhagirathi',
    nearbySensors: [],
    alertStatus: 'WATCH — melt above seasonal baseline (simulated)',
    recommendedAction: 'Continue prototype monitoring of snout and stream gauge.',
  },
  {
    id: 'gl-satopanth',
    kind: 'glacier',
    name: 'Satopanth Glacier',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Chamoli',
    coord: [30.745, 79.4],
    isDemoArea: false,
    coverage: 'full',
    demo: true,
    population: 0,
    elevationM: 4600,
    floodProbability: 66,
    risk: 'elevated',
    leadTimeMin: 110,
    confidence: 58,
    rainfall: 16,
    soilMoisture: 50,
    riverLevel: 1.6,
    riverDanger: 3.8,
    slopeStability: 44,
    historicalRisk: 'High — Alaknanda headwater GLOF exposure (simulated)',
    nearbyRiver: 'Alaknanda',
    nearbySensors: [],
    alertStatus: 'WARNING — ice-dammed pond growth (simulated)',
    recommendedAction: 'Flag downstream Chamoli settlements in prototype playbook.',
  },
  {
    id: 'gl-khatling',
    kind: 'glacier',
    name: 'Khatling Glacier',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Tehri Garhwal',
    coord: [30.48, 79.12],
    isDemoArea: true,
    coverage: 'limited',
    demo: true,
    population: 0,
    elevationM: 3710,
    floodProbability: 39,
    risk: 'caution',
    leadTimeMin: 200,
    confidence: 52,
    rainfall: 20,
    soilMoisture: 62,
    riverLevel: 1.4,
    riverDanger: 3.5,
    slopeStability: 48,
    historicalRisk: 'Moderate — Bhilangna headwaters (simulated)',
    nearbyRiver: 'Bhilangna',
    nearbySensors: [],
    alertStatus: 'WATCH — sparse observation grid (simulated)',
    recommendedAction: 'Limited-confidence prototype; do not treat as an operational product.',
  },
  {
    id: 'gl-pindari',
    kind: 'glacier',
    name: 'Pindari Glacier',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Bageshwar',
    coord: [30.275, 80.008],
    isDemoArea: false,
    coverage: 'full',
    demo: true,
    population: 0,
    elevationM: 3660,
    floodProbability: 34,
    risk: 'caution',
    leadTimeMin: 210,
    confidence: 60,
    rainfall: 24,
    soilMoisture: 58,
    riverLevel: 1.5,
    riverDanger: 3.6,
    slopeStability: 57,
    historicalRisk: 'Moderate — Pindar catchment (simulated)',
    nearbyRiver: 'Pindar',
    nearbySensors: [],
    alertStatus: 'NOMINAL — seasonal melt within envelope (simulated)',
    recommendedAction: 'Maintain prototype watch on snout lakelets.',
  },
  {
    id: 'gl-dokriani',
    kind: 'glacier',
    name: 'Dokriani Glacier',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Uttarkashi',
    coord: [30.85, 78.82],
    isDemoArea: false,
    coverage: 'limited',
    demo: true,
    population: 0,
    elevationM: 3960,
    floodProbability: 55,
    risk: 'elevated',
    leadTimeMin: 140,
    confidence: 55,
    rainfall: 19,
    soilMoisture: 54,
    riverLevel: 1.7,
    riverDanger: 3.9,
    slopeStability: 46,
    historicalRisk: 'Elevated — documented retreat series used as prototype analogue',
    nearbyRiver: 'Bhagirathi tributary',
    nearbySensors: [],
    alertStatus: 'WARNING — melt-rate above baseline (simulated)',
    recommendedAction: 'Use only as demonstration of glacier-driver coupling.',
  },
  // ---- Natural water-body monitoring sites (simulated) ----------------------
  {
    id: 'lk-chorabari-tal',
    kind: 'lake',
    name: 'Chorabari Tal',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    coord: [30.745, 79.075],
    isDemoArea: true,
    coverage: 'full',
    demo: true,
    population: 0,
    elevationM: 3840,
    floodProbability: 78,
    risk: 'critical',
    leadTimeMin: 55,
    confidence: 62,
    rainfall: 28,
    soilMoisture: 70,
    riverLevel: 2.4,
    riverDanger: 3.2,
    slopeStability: 40,
    historicalRisk: 'Severe analogue — 2013 Mandakini outburst corridor (simulated)',
    nearbyRiver: 'Mandakini',
    nearbySensors: [],
    alertStatus: 'CRITICAL — glacial-lake overflow watch (simulated)',
    recommendedAction: 'Prototype GLOF drill for Kedarnath–Gaurikund corridor.',
  },
  {
    id: 'lk-satopanth',
    kind: 'lake',
    name: 'Satopanth Lake',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Chamoli',
    coord: [30.745, 79.359],
    isDemoArea: false,
    coverage: 'full',
    demo: true,
    population: 0,
    elevationM: 4350,
    floodProbability: 61,
    risk: 'elevated',
    leadTimeMin: 120,
    confidence: 57,
    rainfall: 15,
    soilMoisture: 48,
    riverLevel: 1.9,
    riverDanger: 2.8,
    slopeStability: 49,
    historicalRisk: 'Elevated — Alaknanda glacial lake (simulated)',
    nearbyRiver: 'Alaknanda',
    nearbySensors: [],
    alertStatus: 'WARNING — level above seasonal reference (simulated)',
    recommendedAction: 'Track ice-margin dam integrity in the prototype scenario.',
  },
  {
    id: 'lk-vasuki',
    kind: 'lake',
    name: 'Vasuki Tal',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Rudraprayag',
    coord: [30.7, 79.4],
    isDemoArea: true,
    coverage: 'limited',
    demo: true,
    population: 0,
    elevationM: 4235,
    floodProbability: 44,
    risk: 'caution',
    leadTimeMin: 180,
    confidence: 50,
    rainfall: 17,
    soilMoisture: 52,
    riverLevel: 1.3,
    riverDanger: 2.4,
    slopeStability: 54,
    historicalRisk: 'Moderate — high alpine lake, sparse observations (simulated)',
    nearbyRiver: 'Mandakini tributary',
    nearbySensors: [],
    alertStatus: 'WATCH — limited prototype coverage',
    recommendedAction: 'Do not treat sparse alpine readings as operational.',
  },
  {
    id: 'lk-hemkund',
    kind: 'lake',
    name: 'Hemkund',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Chamoli',
    coord: [30.698, 79.617],
    isDemoArea: false,
    coverage: 'full',
    demo: true,
    population: 0,
    elevationM: 4329,
    floodProbability: 29,
    risk: 'caution',
    leadTimeMin: 220,
    confidence: 63,
    rainfall: 21,
    soilMoisture: 56,
    riverLevel: 1.2,
    riverDanger: 2.6,
    slopeStability: 61,
    historicalRisk: 'Low–moderate — cirque lake (simulated)',
    nearbyRiver: 'Lakshman Ganga',
    nearbySensors: [],
    alertStatus: 'NOMINAL — within seasonal band (simulated)',
    recommendedAction: 'Continue prototype water-level series.',
  },
  {
    id: 'lk-tehri',
    kind: 'lake',
    name: 'Tehri Reservoir',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Tehri Garhwal',
    coord: [30.378, 78.48],
    isDemoArea: false,
    coverage: 'full',
    demo: true,
    population: 0,
    elevationM: 830,
    floodProbability: 41,
    risk: 'caution',
    leadTimeMin: 240,
    confidence: 70,
    rainfall: 32,
    soilMoisture: 74,
    riverLevel: 6.1,
    riverDanger: 7.4,
    slopeStability: 72,
    historicalRisk: 'Reservoir operations analogue (simulated — not a live CWC feed)',
    nearbyRiver: 'Bhagirathi',
    nearbySensors: [],
    alertStatus: 'WATCH — catchment rainfall accumulating (simulated)',
    recommendedAction: 'Prototype only; not a dam-safety operational product.',
  },
  {
    id: 'lk-nainital',
    kind: 'lake',
    name: 'Naini Lake',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Nainital',
    coord: [29.392, 79.454],
    isDemoArea: false,
    coverage: 'full',
    demo: true,
    population: 0,
    elevationM: 1938,
    floodProbability: 36,
    risk: 'caution',
    leadTimeMin: 200,
    confidence: 66,
    rainfall: 27,
    soilMoisture: 71,
    riverLevel: 3.4,
    riverDanger: 4.1,
    slopeStability: 63,
    historicalRisk: 'Urban lakeshore inundation analogue (simulated)',
    nearbyRiver: 'Balia Nala',
    nearbySensors: [],
    alertStatus: 'WATCH — monsoon stage rising (simulated)',
    recommendedAction: 'Prototype urban lake-level demonstration.',
  },
  {
    id: 'lk-kedartal',
    kind: 'lake',
    name: 'Kedartal',
    country: 'India',
    state: 'Uttarakhand',
    district: 'Uttarkashi',
    coord: [30.9, 78.94],
    isDemoArea: false,
    coverage: 'limited',
    demo: true,
    population: 0,
    elevationM: 4725,
    floodProbability: 58,
    risk: 'elevated',
    leadTimeMin: 130,
    confidence: 49,
    rainfall: 14,
    soilMoisture: 47,
    riverLevel: 1.5,
    riverDanger: 2.2,
    slopeStability: 43,
    historicalRisk: 'Glacial lake below Kedar dome (simulated)',
    nearbyRiver: 'Kedar Ganga',
    nearbySensors: [],
    alertStatus: 'WARNING — anomaly vs reference level (simulated)',
    recommendedAction: 'Limited-confidence alpine prototype record.',
  },
]

export const locations: Record<string, LocationRecord> = Object.fromEntries(
  records.map((r) => [r.id, r]),
)

export const locationList: LocationRecord[] = records

export const DEFAULT_LOCATION_ID = 'v-1'

export function getLocation(id: string | null): LocationRecord | null {
  if (!id) return null
  return locations[id] ?? null
}

// Seed a live-telemetry baseline from a location record so the simulation and
// charts always correspond to the currently selected location.
export function metricsForLocation(loc: LocationRecord): LiveMetrics {
  return {
    rainfall: loc.rainfall,
    soilMoisture: loc.soilMoisture,
    slopeStability: loc.slopeStability,
    riverLevel: loc.riverLevel,
    riverDanger: loc.riverDanger,
    floodProbability: loc.floodProbability,
    leadTimeMin: loc.leadTimeMin,
    confidence: loc.confidence,
    updatedAt: 0,
  }
}
